site :opscode
cookbook 'git'
cookbook 'zsh'
cookbook 'yum'
cookbook 'tmux'
cookbook 'vim'
cookbook 'openssh'
cookbook 'curl'
cookbook 'simple_iptables'
cookbook 'ntp'
cookbook 'sudo'
cookbook 'users'
cookbook 'nginx'
cookbook 'php-fpm'
cookbook 'chef-solo-search', github: 'edelight/chef-solo-search.git'
